### PR TITLE
Add "Leveraging FINOS to Build Flourishing Projects and SIGs" to FINOS Community Repo

### PR DESCRIPTION
**Pull request by mcleo-d**
## Description

This pull requests adds the content of the **Leveraging FINOS to Build Flourishing Projects and SIGs** presentation to the FINOS Community repo that was given to FINOS Project and SIG leads on Thursday 3rd March 2022.

The intention of this content is for it to be referred to by FINOS Project and SIG leads, whilst inviting feedback and pull requests for future iterations and release.

### Markdown
This pull request includes the following hypertext documentation as `markdown`.

1. FINOS Community 2022 Strategic Overview
2. Communicate WHY and HOW the FINOS Community should contribute
3. Provide an amazing engineering experience for first time contributors
4. Coordinate work through GitHub Issues, Discussions and FINOS Slack
5. Create an Open Profile to Benefit Maintainers and Contributors
6. Measure FINOS Project and SIG Success with LFX Insights
7. Work with FINOS to Recognise Community Achievements
8. Ensure FINOS Project Security with LF Security Training and OpenSSF

### PDF Download
This pull request also commits the following `PDF` into the FINOS Community repo that is referred to for download.

[finos-2022-community-strategy-public.pdf](https://github.com/finos/community/files/8205605/finos-2022-community-strategy-public.pdf)

### CODE REVIEW

**Comment by mcleo-d** [comment]
@agitana and @mindthegab - It would be great if you could review and merge this PR given the work that's happening on the Community repo at the moment. 

The intention is to engage FINOS leads in the education and evolution of the FINOS 2022 Community Strategy, where having this content in the FINOS organisation will be extremely beneficial.

Apologies for the commit names, I wanted to get the content into the repo, so went for speed of commit over the commit naming. This isn't my usual approach.

Thanks for your help and support.

James.

**Comment by agitana** [comment]
LGTM @mcleo-d , nice job! I suggest we build this content into the community site once it's ready to go live. Thank you!

**Comment by ffionwiggins** [comment]
Is there a central place (or does github do it for us that I need to learn about!) that details who the contacts are per member firms and one step further which SIGs/Working GRoups they are currently engaged in?

**Comment by mindthegab** [comment]
> Is there a central place (or does github do it for us that I need to learn about!) that details who the contacts are per member firms and one step further which SIGs/Working GRoups they are currently engaged in?

Hey @ffionwiggins - great questions. Contacts per Member firm are added to the "per tier" (platinum-members@finos.org, gold-members@finos.org, silver-members@finos.org) membership lists in Google Groups, and members of those groups can see other Members (assuming they can login in Google Groups).

Re which SIG and WG they are involved in, our [Project activity dashboard](https://insights.lfx.linuxfoundation.org/projects/finos/dashboard;subTab=technical;v=project-activities%2Ffinoscommunity%2Ffinosproject?filter=%23%2Fdashboard%2Ffffbcb40-71d0-11eb-af30-0df96ab653b0%3Fembed%3Dtrue%26_g%3D(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:%27now-90d%27,to:%27now%27))%26_a%3D(description:%27%27,filters:!((%27$state%27:(store:appState),meta:(alias:%27ML%2520Forwards%27,disabled:!f,index:git,key:query,negate:!t,type:custom,value:%27%257B%2522wildcard%2522:%257B%2522From_name%2522:%2522*%2520via%2520*%2522%257D%257D%27),query:(wildcard:(From_name:%27*%2520via%2520*%27))),(%27$state%27:(store:appState),meta:(alias:%27Automated%2520Reports%27,disabled:!f,index:git,key:author_name,negate:!t,params:(query:%27FINOS%2520Automated%2520Reports%27),type:phrase),query:(match_phrase:(author_name:%27FINOS%2520Automated%2520Reports%27))),(%27$state%27:(store:appState),meta:(alias:%27FINOS%2520Staff%27,disabled:!f,index:%27434c7a20-9b70-11eb-94e8-4323c8335d1a%27,key:author_org_name,negate:!t,params:!(FINOS,%27The%2520Linux%2520Foundation%27,%27Symphony%2520Software%2520Foundation%27),type:phrases,value:%27FINOS,%2520The%2520Linux%2520Foundation,%2520Symphony%2520Software%2520Foundation%27),query:(bool:(minimum_should_match:1,should:!((match_phrase:(author_org_name:FINOS)),(match_phrase:(author_org_name:%27The%2520Linux%2520Foundation%27)),(match_phrase:(author_org_name:%27Symphony%2520Software%2520Foundation%27)))))),(%27$state%27:(store:appState),meta:(alias:Bots,disabled:!f,index:git,key:author_bot,negate:!t,params:(query:!t),type:phrase),query:(match_phrase:(author_bot:!t))),(%27$state%27:(store:appState),meta:(alias:%27Repository%2520Level%2520Activity%27,disabled:!f,index:%27434c7a20-9b70-11eb-94e8-4323c8335d1a%27,key:type,negate:!t,params:(query:repository),type:phrase),query:(match_phrase:(type:repository))),(%27$state%27:(store:appState),meta:(alias:%27Empty%2520Commits%27,disabled:!f,index:git,key:files,negate:!t,params:(query:%270%27),type:phrase),query:(match_phrase:(files:%270%27))),(%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:%27434c7a20-9b70-11eb-94e8-4323c8335d1a%27,key:project,negate:!f,params:(query:Legend),type:phrase),query:(match_phrase:(project:Legend)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),panels:!((embeddableConfig:(title:%27About%2520Filters%27),gridData:(h:3,i:%2743dfe13a-5852-4453-ba6f-ddfdf9bb137d%27,w:48,x:0,y:0),id:c13be510-cd39-11eb-bf76-cb2bce839a2b,panelIndex:%2743dfe13a-5852-4453-ba6f-ddfdf9bb137d%27,title:%27About%2520Filters%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(),gridData:(h:16,i:e1e1a758-a244-4a7a-8c17-51a288b2c414,w:16,x:13,y:3),id:b553b0f0-9b72-11eb-9005-3930817a030d,panelIndex:e1e1a758-a244-4a7a-8c17-51a288b2c414,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27Project%2520Activity%2520Summary%27),gridData:(h:16,i:%279dcbcd64-cc09-46b1-9f85-f604a91f6182%27,w:19,x:29,y:3),id:%2776996c90-9b74-11eb-9005-3930817a030d%27,panelIndex:%279dcbcd64-cc09-46b1-9f85-f604a91f6182%27,title:%27Project%2520Activity%2520Summary%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(params:(sort:(columnIndex:1,direction:asc)),title:%27Contributions%2520by%2520Individual%27,vis:(params:(sort:(columnIndex:1,direction:desc)))),gridData:(h:19,i:%27042c4964-1a93-4144-876e-55c2a86883a9%27,w:48,x:0,y:19),id:%2732041040-9b78-11eb-94e8-4323c8335d1a%27,panelIndex:%27042c4964-1a93-4144-876e-55c2a86883a9%27,title:%27Contributions%2520by%2520Individual%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(params:(sort:(columnIndex:1,direction:asc)),title:%27Contributions%2520by%2520Organization%27,vis:(params:(sort:(columnIndex:1,direction:desc)))),gridData:(h:18,i:%27995684aa-0c3f-4c12-b165-dbc0ec1517f5%27,w:48,x:0,y:38),id:%2748acd840-9b78-11eb-94e8-4323c8335d1a%27,panelIndex:%27995684aa-0c3f-4c12-b165-dbc0ec1517f5%27,title:%27Contributions%2520by%2520Organization%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:%27Contributions%2520by%2520Projects%27),gridData:(h:20,i:f0902d05-27ae-4e87-b888-82f7fd613d28,w:24,x:0,y:56),id:%27638b3840-f06a-11eb-bd79-f3db3ff39743%27,panelIndex:f0902d05-27ae-4e87-b888-82f7fd613d28,title:%27Contributions%2520by%2520Projects%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(),gridData:(h:20,i:%279a6104b4-6243-4848-961c-f9823d84d460%27,w:24,x:24,y:56),id:%275217ed60-9b79-11eb-94e8-4323c8335d1a%27,panelIndex:%279a6104b4-6243-4848-961c-f9823d84d460%27,type:visualization,version:%277.6.2%27),(embeddableConfig:(title:Filter),gridData:(h:16,i:c89a535f-97ef-41c7-bd88-e40860090c41,w:13,x:0,y:3),id:%27622700e0-0fc5-11ec-af44-59b12280013e%27,panelIndex:c89a535f-97ef-41c7-bd88-e40860090c41,title:Filter,type:visualization,version:%277.6.2%27)),query:(language:kuery,query:%27%27),timeRestore:!f,title:%27Project%2520Activities%27,viewMode:view)&time=%7B%22from%22:%22now-90d%22,%22type%22:%22datemath%22,%22to%22:%22now%22%7D) has this information, and you can filter by project (clicking on the tag cloud) and then we're happy to make intros (you won't find an email there for privacy reasons).

Hope this helps!

**Review by mindthegab — APPROVED** [review]
The content looks good - we discussed merging this in the Community docusaurus website, so happy to review an additional PR once available or OK for this to be merged if that makes more sense workflow wise.

**Review by mindthegab — APPROVED** [review]

**Comment by mcleo-d** [comment]
> The content looks good - we discussed merging this in the Community docusaurus website, so happy to review an additional PR once available or OK for this to be merged if that makes more sense workflow wise.

The content of this pull request has now been merged into the [FINOS Community Microsite](https://community.finos.org/) and the PR has been merged based on the workflow comment made by @mindthegab.

The additional sections `growing-your-project-community -> finos-community-strategy` have been added to the FINOS Community Microsite as part of the change.

**Pull request merged**
