### PR TITLE
Contribute pages

### PR DESCRIPTION
**Pull request by maoo**
Moved content from https://finosfoundation.atlassian.net/wiki/ re. FINOS Contribution process.

### CODE REVIEW

**Review by mindthegab — COMMENTED** [review]
LGTM

**Comment by mindthegab** [comment]
Merging pull request to include new contribute page! Great stuff @maoo. @toshaellison if you can take a look at the EasyCLA page it would be fantastic.

**Comment by toshaellison** [comment]
@mindthegab Reviewed EasyCLA and made minor changes, thanks @maoo for updating it. One question, towards the bottom where there is sample text to add to projects should that link point to info about EasyCLA or to our CLAs?

"Project participants must sign the free [FINOS CLA](https://github.com/finos/<your repo>) before making a contribution. You only need to do this one time, and it can be signed by individual contributors or their employers."

**Comment by maoo** [comment]
@toshaellison - WDYT of https://github.com/finos/community/commit/08b0388c88d9e89e8e305ae801919947e7a727c5 ?

**Pull request merged**
