### PR TITLE
Add a Community Recognition GitHub Issue Template to the FINOS Community Repo

### PR DESCRIPTION
**Pull request by mcleo-d**
# Description
This pull request adds a community recognition issue template that allows the FINOS community to recognise the work thats happening within the FINOS community.

This feedback mechanism will be referred to in the FINOS newsletter being sent on 18th December 2020.

# Template Markdown

```
---
name: "👏🏻 💯💯💯 FINOS Community Recognition"
about: Recognise members of the FINOS Community
title: FINOS Community Recognition
assignees: mcleo-d
labels: community-recognition
---

## Who in the FINOS Community would you like to recognise?
Let FINOS know who you'd like to recognise in the FINOS Community by providing the following information in your GitHub issue.  

- The person or people in the FINOS Community you'd like to recognise
- The GitHub profiles of the recognised person or people 
- The FINOS projects, special interest groups, meetups, events ... etc where they contribute to FINOS
- The reason why they've been recognised 

## Show the FINOS Community the difference they've made

Feel free to link FINOS projects, code examples, pull requests, issue threads, uploaded photos and screenshots that demonstrate the great work you're recognising.  

Thank you for recognising the FINOS Community.

The FINOS Team.
```

# Template Preview

## Who in the FINOS Community would you like to recognise?
Let FINOS know who you'd like to recognise in the FINOS Community by providing the following information in your GitHub issue.  

- The person or people in the FINOS Community you'd like to recognise
- The GitHub profiles of the recognised person or people 
- The FINOS projects, special interest groups, meetups, events ... etc where they contribute to FINOS
- The reason why they've been recognised 

## Show the FINOS Community the difference they've made

Feel free to link FINOS projects, code examples, pull requests, issue threads, uploaded photos and screenshots that demonstrate the great work you're recognising.  

Thank you for recognising the FINOS Community.

The FINOS Team.

### CODE REVIEW

**Comment by toshaellison** [comment]
Looks good, James. Is it worth also adding a label to the template so that we/community can easily see all of the recognition issues that have been posted.

Is there any sort of validation required? What will happen once individuals have been recognized through a GH recognition issue? Might these "recognitions" be referenced in TWAF and FINOS newsletters? Will there be any swag involved, which would require some level of validation?

**Comment by mcleo-d** [comment]
Hi @toshaellison

Thanks so much for your feedback. I hope the detail below helps answer.

> Is it worth also adding a label to the template so that we/community can easily see all of the recognition issues that have been posted.

A label named `community-recognition` has been added to the community repository and the issue template as highlighted below. This means the label will be automatically applied when a **Community Recognition** is raised as an issue. 

```
labels: community-recognition
```

> Is there any sort of validation required? What will happen once individuals have been recognized through a GH recognition issue? Might these "recognitions" be referenced in TWAF and FINOS newsletters? Will there be any swag involved, which would require some level of validation?

Each Commuting Recognition will be assigned to @mcleo-d as the `Assignee`, which is the first level of validation. Within the issue itself, each person being recognised is also tagged with their GitHub profile, like @toshaellison. The person who is recognising is also known, as they have raised the issue.

```
assignees: mcleo-d
```

Within the content of the Community Recognition, the person raising the issue should link FINOS projects, code examples, pull requests, issue threads, uploaded photos and screenshots that demonstrate the work being recognised.  This will help provide context, plus also really highlights the great work of the FINOS Community.

Once recognitions have been raised, these can be referred to in This Week at FINOS, Community Spotlight, FINOS Newsletters, FINOS All Community Calls and OSSF Awards. Swag can also be sent, but the swag thresholds still need to be discussed.

The objective is to bring the community together by highlighting the deeply nested work that's happening, but that often gets overlooked through the day to day nature of writing software and solving problems.

**Review by mindthegab — COMMENTED** [review]
LGTM!

**Comment by toshaellison** [comment]
Great, thanks @mcleo-d for the detailed feedback. One more thing. Do we need to add guidance (even if minimal) anywhere, e.g in Community Handbook, on what is eligible? I know you have this in the template but I wonder if a more "official" reference point would be valuable. I'm thinking about avoiding unforeseen (and likely very low risk) consequences of receiving highlights for items outside of FINOS related activities.

**Comment by mcleo-d** [comment]
PR merged following a next steps conversation with @toshaellison

**Pull request merged**
