### PR TITLE
Blending OpenSSF Badge `Pass` Criteria into FINOS `Active` Project Criteria

### PR DESCRIPTION
**Pull request by mcleo-d**
## Description 
This pull request blends the Linux Foundation OpenSSF Badge `Pass` criteria into the FINOS `Active` project criteria so all FINOS `Active` projects earn the OpenSSF badge when activated.

Please find more details about OpenSSF and the OpenSSF Badge below.

- https://openssf.org/
- https://bestpractices.coreinfrastructure.org/
- https://bestpractices.coreinfrastructure.org/en/criteria/0

### CODE REVIEW

**Comment by robmoffat** [comment]
My main comment on this is that `active` is already a very high bar.  If you _really_ look at the landscape, there are perhaps only two projects that meet this criteria.  

I personally think the lifecycle may be a little binary.

**Comment by robmoffat** [comment]
is there a deploy preview of this, I don't see it

**Comment by mcleo-d** [comment]
> is there a deploy preview of this, I don't see it

I'll kick off `netflify` as the `md` changes didn't seem to trigger a new preview build. Thanks for letting me know 👍🏻

**Comment by robmoffat** [comment]
> > is there a deploy preview of this, I don't see it
> 
> I'll kick off `netflify` as the `md` changes didn't seem to trigger a new preview build. Thanks for letting me know 👍🏻

any luck?

Having gone through the OpenSSF badge process now, I think it boils down to:

a) stuff all projects will be doing anyway
b) some stuff it'd be sensible to do
c) some weird stuff which luckily seems optional to getting the badge.

It's not as onerous as it looked on first pass.

**Review by robmoffat — APPROVED** [review]

**Comment by mcleo-d** [comment]
Congrats on passing the OpenSSF badge `pass` criteria for [spring-bot](https://github.com/finos/spring-bot/tree/spring-bot-develop) @robmoffat 

Screenshot 2022-04-14 at 22 13 56

**Comment by robmoffat** [comment]
Github has a tab for security

Screenshot 2022-04-22 at 10 12 24

As you can see, I've got this to show three green dots for Spring-bot.  There's not much beyond what is required for OpenSSF, but it's a nice check that you're doing things right.

I think our `active` badge should require these three green dots, in addition to OpenSSF.

**Comment by mindthegab** [comment]
@mcleo-d Thanks for this. This is one the PR I suggest we leave open for the [Pilot TSC]( #162) to evaluate.

**Comment by ColinEberhardt** [comment]
Hi @mcleo-d I'll take a look at this and determine how we might bring it to the @finos/technical-steering-committee for consideration.

**Comment by ColinEberhardt** [comment]
Hi @mcleo-d this was discussed in a [recent TSC meeting](https://github.com/finos/technical-steering-committee/blob/master/meetings/2022-09-29.md#finos-infrastructure-contributions). As a group, we are very positive about this FINOS infrastructure change. However, we don't envisage getting involved in the detailed implementation. I'd suggest peer-review within the FINOS team as a next step, or to simply give it a try ...

**Comment by maoo** [comment]
I have reviewed the changes; I see that there are a lot of indentation changes, which in my opinion should not be part of the Pull Request, as it makes it hard to understand what really changed.

The new contents that I see are:
- in `Active.md`, a new paragraph titled `Obtaining the OpenSSF Best Practices Badge`
- in `Active.md`, a new table entry called `Status Badging`

In `Incubating.md` I only see formatting changes, so I'd revert everything.

In `OpenSSF-Criteria-Passing.md` I see a copy of all questions mentioned in the Passing Badge; I'd suggest not to replicate such content, because otherwise we'd be responsible to update it everytime that there's change in OpenSSF questions, which is not ideal. So, I'd suggest to get rid of this page.

**Comment by robmoffat** [comment]
@maoo said: 

> In OpenSSF-Criteria-Passing.md I see a copy  ... So, I'd suggest to get rid of this page.

I agree, we shouldn't dup that.

@robmoffat said:

> My main comment on this is that active is already a very high bar. If you really look at the landscape, there are perhaps only two projects that meet this criteria.

This is still true, but having got used to OpenSSF, I think it's actually a very reasonable set of questions.  The bar is already high for other reasons.  

I say we should merge this and use it to draw attention to OpenSSF from the community

**Comment by maoo** [comment]
Thanks @robmoffat - I've reapplied changes, removing formatting updates and the page that lists the badge criteria (which is also available on https://github.com/coreinfrastructure/best-practices-badge#summary-of-best-practices-criteria-passing-level)

Could you please review https://github.com/finos/community/compare/openssf-criteria-2?expand=1 ? I've also made some changes to the content (explained what OpenSSF Badge is, and updated links)

**Comment by robmoffat** [comment]
Hi @maoo,

I'm confused by the workflow here - is this a new PR to replace the first PR?  Or a PR onto James' original branch?  or... not a PR?

**Comment by maoo** [comment]
> Hi @maoo,
> 
> I'm confused by the workflow here - is this a new PR to replace the first PR? Or a PR onto James' original branch? or... not a PR?

It's a parallel branch, so the idea is - as soon as you review the changes - to close this PR, create a new one from https://github.com/finos/community/compare/openssf-criteria-2?expand=1  and merge it right away.

In terms of real changes, the 2 branches are pretty much the same.

**Comment by robmoffat** [comment]
Used #211 instead

**Pull request closed without merging**
